source 'https://rubygems.org'

gem 'rake'
gem 'tzinfo-data'
gem 'rufus-scheduler'
gem 'yamazaki'
gem 'foreverb'
gem 'terminal-notifier'
gem 'libnotify'
gem 'rb-notifu'
gem 'filewatcher'
gem 'ruby_deep_clone'

gem 'cucumber'
gem 'rspec'